/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.ControladorEntrada;
import controlador.Estilos;


public class Frm_Dias extends javax.swing.JInternalFrame {

    Estilos style = new Estilos();
    public Frm_Dias() {
        initComponents();
        txtbuscador.setBackground(new java.awt.Color(0, 0, 0, 1));
        style.estiloTabla(Tabla);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuItemEliminar = new javax.swing.JMenuItem();
        menuItemEditar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtbuscador = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar4 = new javax.swing.JButton();

        menuItemEliminar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuItemEliminar.setForeground(new java.awt.Color(255, 0, 0));
        menuItemEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        menuItemEliminar.setText("Eliminar Registro");
        menuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuItemEliminar);

        menuItemEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        menuItemEditar.setText("Editar el dìa");
        menuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuItemEditar);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Días Registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 48))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Dia", "ID Soporte", "Apellidos", "Nombres", "Fecha Ingreso", "Hora Ingreso", "Fecha Salida", "Hora Salida", "Total de Horas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setComponentPopupMenu(jPopupMenu1);
        Tabla.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane2.setViewportView(Tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 910, 380));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        txtbuscador.setBackground(new java.awt.Color(0, 0, 0));
        txtbuscador.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtbuscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbuscador.setBorder(null);
        txtbuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscadorKeyReleased(evt);
            }
        });
        jPanel1.add(txtbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 310, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 98, 236));
        jSeparator3.setForeground(new java.awt.Color(0, 98, 236));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 310, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 50, 50));

        btnCerrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/espalda.png"))); // NOI18N
        btnCerrar4.setText("Regresar");
        btnCerrar4.setBorder(null);
        btnCerrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscadorKeyReleased
        // TODO add your handling code here:
        ControladorEntrada obj = new ControladorEntrada(this);
        obj.actionPerformed(evt);        
    }//GEN-LAST:event_txtbuscadorKeyReleased

    private void btnCerrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrar4ActionPerformed

    private void menuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarActionPerformed
        // TODO add your handling code here:
        ControladorEntrada obj = new ControladorEntrada(this);
        obj.actionPerformed(evt);
    }//GEN-LAST:event_menuItemEliminarActionPerformed

    private void menuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarActionPerformed
        // TODO add your handling code here:
        ControladorEntrada obj = new ControladorEntrada(this);
        obj.actionPerformed(evt);
    }//GEN-LAST:event_menuItemEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tabla;
    private javax.swing.JButton btnCerrar4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JMenuItem menuItemEditar;
    public javax.swing.JMenuItem menuItemEliminar;
    public javax.swing.JTextField txtbuscador;
    // End of variables declaration//GEN-END:variables
}
