package vista;

import controlador.ControladorSoporte;
import controlador.Estilos;
import javax.swing.JOptionPane;

public class FrmVer_Soporte extends javax.swing.JInternalFrame {

    Estilos style = new Estilos();

    public FrmVer_Soporte() {
        initComponents();
        style.estiloTabla(tabla);
        txtbuscador.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        menuItemEditar = new javax.swing.JMenuItem();
        menuItemEliminar = new javax.swing.JMenuItem();
        menuItemAgregarDia = new javax.swing.JMenuItem();
        panelVerSoporte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtbuscador = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        btnListarSoporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        popMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        popMenu.setPreferredSize(new java.awt.Dimension(180, 100));

        menuItemEditar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuItemEditar.setForeground(new java.awt.Color(51, 153, 255));
        menuItemEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        menuItemEditar.setText("Modificar Soporte");
        menuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarActionPerformed(evt);
            }
        });
        popMenu.add(menuItemEditar);

        menuItemEliminar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuItemEliminar.setForeground(new java.awt.Color(255, 0, 0));
        menuItemEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        menuItemEliminar.setText("Eliminar Soporte");
        menuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarActionPerformed(evt);
            }
        });
        popMenu.add(menuItemEliminar);

        menuItemAgregarDia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuItemAgregarDia.setForeground(new java.awt.Color(51, 153, 255));
        menuItemAgregarDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario.png"))); // NOI18N
        menuItemAgregarDia.setText("Agregar Dia");
        menuItemAgregarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgregarDiaActionPerformed(evt);
            }
        });
        popMenu.add(menuItemAgregarDia);

        panelVerSoporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        panelVerSoporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Soporte", "Apellidos", "Nombres", "DNI", "Domicilio", "Fecha Nacimiento", "Correo", "Celular", "Turno", "Total Horas", "Estado", "Foto"
            }
        ));
        tabla.setComponentPopupMenu(popMenu);
        tabla.setFocusable(false);
        tabla.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabla.setShowVerticalLines(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        panelVerSoporte.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1100, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Soportes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscador.setBackground(new java.awt.Color(0, 0, 0));
        txtbuscador.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtbuscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbuscador.setBorder(null);
        txtbuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscadorKeyReleased(evt);
            }
        });
        jPanel2.add(txtbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 310, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 98, 236));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 310, 20));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/espalda.png"))); // NOI18N
        btnCerrar.setText("Regresar");
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 120, 50));

        btnListarSoporte.setText("Listar Soportes");
        btnListarSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarSoporteActionPerformed(evt);
            }
        });
        jPanel2.add(btnListarSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 250, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVerSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelVerSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarSoporteActionPerformed
        // TODO add your handling code here:
        ControladorSoporte obj = new ControladorSoporte(this);
        obj.actionPerformed(evt);
    }//GEN-LAST:event_btnListarSoporteActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void menuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarActionPerformed
        // TODO add your handling code here:
        ControladorSoporte obj = new ControladorSoporte(this);
        obj.actionPerformed(evt);
    }//GEN-LAST:event_menuItemEditarActionPerformed

    private void menuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Eliminar el soporte?", "Eliminar", dialogButton);
        if (result == 0) {
            ControladorSoporte obj = new ControladorSoporte(this);
            obj.actionPerformed(evt);
        }
    }//GEN-LAST:event_menuItemEliminarActionPerformed

    private void txtbuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscadorKeyReleased
        // TODO add your handling code here:
        ControladorSoporte obj = new ControladorSoporte(this);
        obj.actionPerformed(evt);
    }//GEN-LAST:event_txtbuscadorKeyReleased

    private void menuItemAgregarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgregarDiaActionPerformed
        // TODO add your handling code here:
        ControladorSoporte obj = new ControladorSoporte(this);
        obj.actionPerformed(evt);
        
        
    }//GEN-LAST:event_menuItemAgregarDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnListarSoporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JMenuItem menuItemAgregarDia;
    public javax.swing.JMenuItem menuItemEditar;
    public javax.swing.JMenuItem menuItemEliminar;
    private javax.swing.JPanel panelVerSoporte;
    private javax.swing.JPopupMenu popMenu;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtbuscador;
    // End of variables declaration//GEN-END:variables
}
