package vista;

import controlador.ControladorEntrada;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public Login() {
        initComponents();
        tamano();
        txtuser.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtpassword.setBackground(new java.awt.Color(0, 0, 0, 1));
        btnConectar.setBorderPainted(false);
        btnConectar.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtuser.requestFocus();

    }

    private void tamano() {

        this.setSize(400, 560);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        lblUserError = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        btnConectar = new javax.swing.JButton();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 140, 40));

        txtuser.setBackground(new java.awt.Color(16, 16, 16));
        txtuser.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuser.setBorder(null);
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuserKeyReleased(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, 30));

        jSeparator1.setBackground(new java.awt.Color(1, 108, 58));
        jSeparator1.setForeground(new java.awt.Color(1, 108, 58));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 360, 20));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 30));

        txtpassword.setBackground(new java.awt.Color(16, 16, 16));
        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(null);
        txtpassword.setPreferredSize(new java.awt.Dimension(7, 19));
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 360, 30));

        jSeparator2.setBackground(new java.awt.Color(1, 108, 58));
        jSeparator2.setForeground(new java.awt.Color(1, 108, 58));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 360, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 150, 20));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, -1));

        lblUserError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUserError.setForeground(new java.awt.Color(255, 0, 0));
        lblUserError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblUserError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 350, 20));

        lblPasswordError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblPasswordError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblPasswordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 360, 20));

        btnConectar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConectar.setForeground(new java.awt.Color(255, 255, 255));
        btnConectar.setText("Conectarse");
        btnConectar.setBorder(null);
        btnConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 130, 30));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infologo.png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Salir del Login?", "Salir", dialogButton);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        ControladorEntrada obj = new ControladorEntrada(this);
        if (txtuser.getText().equals("")) {
            lblUserError.setText("Ingrese el usuario");
        }
        if (String.valueOf(txtpassword.getPassword()).equals("")) {
            lblPasswordError.setText("Ingrese la contraseña");
        }
        if (!txtuser.getText().equals("") && !String.valueOf(txtpassword.getPassword()).equals("")) {
            obj.actionPerformed(evt);
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void txtuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyReleased
        // TODO add your handling code here:
        if (txtuser.getText().trim().equals("")) {

            lblUserError.setText("Ingrese el usuario");
        } else {
            lblUserError.setText("");
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtpassword.requestFocus();
        }
    }//GEN-LAST:event_txtuserKeyReleased

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
        // TODO add your handling code here:
        if (String.valueOf(txtpassword.getPassword()).equals("")) {
            lblPasswordError.setText("Ingrese la contraseña");
        }
        if (!String.valueOf(txtpassword.getPassword()).trim().equals("")) {
            lblPasswordError.setText("");
        }
        if (!txtuser.getText().equals("") && !String.valueOf(txtpassword.getPassword()).equals("")) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                ControladorEntrada obj = new ControladorEntrada(this);
                obj.actionPerformed(evt);
            }
        }
    }//GEN-LAST:event_txtpasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConectar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblUserError;
    public javax.swing.JPasswordField txtpassword;
    public javax.swing.JTextField txtuser;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
